### ISSUE TITLE
Если на сессии 3 раза зайти в 204, то все двери закрываются

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2018-2-2d-game#58]
Даже если набран необходимый минимум в 60 % по всем предметам и после этого 3 раза зайти в 204 комнату, то все двери закрываются и игрок входит в тупиковое положение.

**Comment by Mazdaywik** [comment]
**Ожидаемое поведение:** на сессии можно заходить сколько угодно раз в 204 без каких-либо проблем.

**Comment by ghost** [comment]
Исправлено
