### ISSUE TITLE
Если на сессии 5 раз зайти в одну дверь, то вылезает сообщение «Вы успешно сдали все экзамены»

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2018-2-2d-game#59]
Если набрать необходимый минимум 60 % по всем дисциплинам и на сессии 5 раз войти в одну дверь (я входил в 201), то появляется сообщение «Вы успешно сдали все экзамены».

Если после этого зайти в любую дверь, то появляется сообщение: «Вы не закрыли сессию/Видно не судьба/видно не судьба».

**Comment by Mazdaywik** [comment]
**Ожидаемое поведение:** на сессии посещение аудитории, где экзамен уже сдан, ни на что не влияет. Для получения сообщения «Вы успешно сдали все экзамены» (или «Вы не закрыли сессию») нужно посетить все 5 аудиторий. После появления плашки с результатом заход в аудитории и проходные должен блокироваться (как в<span> </span>#58).

**Comment by ghost** [comment]
Исправлено, однако теперь во время сессии можно зайти в любой кабинет (кроме 204) не более одного раза, как и в остальные дни. После появления окна с результатом планируем сделать так, чтобы игра останавливалась (блокировалось движение персонажа).

**Comment by ghost** [comment]
Так вроде нормально
