### ISSUE TITLE
В аудиториях 205 и 206 нет преподавателей

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2018-2-2d-game#60]
Это так и должно быть?

**Comment by GaMbbbYrGeR** [comment]
Да, так как это общеобразовательные предметы и преподаватели по ним у нас постоянно меняются, мы не добавляли спрайтов преподавателей умышленно

**Comment by ghost** [comment]
Это общеобразовательные предметы, но мы добавим их [преподавателей] позже

**Comment by ghost** [comment]
Добавили
