### ISSUE TITLE
Игровой процесс

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-2-2d-game#62]
1.Внутри университета есть два коридора проход в которые заблокирован "невидимой стеной".
2.Если игра проиграна, то сообщение "Видно не судьба" выводится два раза, причем второй раз оно начинается с маленькой буквы.
3.При нажатии буквы P можно поставить игру на паузу, причем непонятно зачем такая функция нужна, более того, она нигде не заявлена.
4.После окончания игры персонаж все еще имеет возможность двигаться.
5.Существует домик, в правом нижнем углу ничем внешне не отличающийся от "нашего", однако зайти в него не получается.
При тестировании использовался браузер Google Chrome

**Comment by Lanaken** [comment]
P.S. Отдельное спасибо за модельки преподавателей :)

**Comment by Lanaken** [comment]
Ожидаемое поведение:
1.Если есть открытые коридоры, значит по ним можно беспрепятственно пройти.
2.Сообщение должно выводится 1 раз с большой буквы.
3.Пауза в данном игровом процессе не нужна. Так как игра пошаговая и не проходит в реальном времени.
4.После окончания игры управление персонажем должно блокироваться.
5.Если существует такой же домик значит, в него можно войти, иначе он должен выглядеть как то по-другому.

**Comment by ghost** [comment]
1. Сообщение в две строчки — это не баг :)
2. Для правого домика разумнее всего будет сделать так, чтобы через него и выйти тоже было нельзя, а как это обозначить мы продумаем.

Все остальное исправим, спасибо :)

**Comment by Mazdaywik** [comment]
(5) В правый домик, вообще-то, зайти можно (заходить надо сверху вниз) и игрок возвращается в свою комнату. По сюжету игры это две проходные. Всё нормально.

**Comment by ghost** [comment]
Все проблемы решены
